### ISSUE TITLE
Use stored operations

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#1643]
Use stored operation when sending queries in production instead of sending operation text.

We are still waiting on the server to be ready, but the work is in progress, so it should not be too long. 

- [ ] as part of `codePush.js` script, we should generate persisted queries, and send them to the server. 
- [ ] In `fetchFormTheNetwork` function, we need to check if query id is available and send that instead of operation text

**Comment by mrtnzlml** [comment]
Do you still want to keep working on this? I kind of stopped working on it on our side since seemed like nobody is going to use it. Will be happy to see our first user ready though... 😊

We can discuss it privately how to make it work without breaking the mobile app in case something goes horribly wrong.

**Comment by tbergq** [comment]
Yes, I also have all the details ready on a private branch, without kiwicom-relay-compiler 🙈 

Let's discuss the details privately yes. 

> case something goes horribly wrong

This is the beauty of code-push, we can just revert bundle, and go back to prior state instantly

**Comment by tbergq** [comment]
Looks like this is not going to happen 😞
