### ISSUE TITLE
Flight services

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#522]
[Specification in confluence](https://confluence.kiwi.com/display/MOB/Manage+my+booking+specification#Managemybookingspecification-Flightservices)
[Zeplin](https://zpl.io/b6JPdGy)
![img](https://cdn.zeplin.io/59a9818fe86dfd4f75f2c142/screens/80836E5F-8AC6-4C23-BCB9-AD2A91A88B92.png)

## Screenshot from current app

![img_5070](https://user-images.githubusercontent.com/7705041/39982420-9b4d59b4-5754-11e8-8617-bd8f132ddcd1.PNG)

## Tasks 
- [x] add component
- [x] connect webviews
- [x] separate ordered/not ordrered
- [x] pull to refresh

## Questions
- Icons?
- Urls to webviews?
- When should this modal open?
![skjermbilde 2018-05-03 kl 15 05 20](https://user-images.githubusercontent.com/7705041/39578069-6f85a832-4ee3-11e8-81b1-9cdce90a305c.png)
- How do we know if a service has been ordered?
- Is there any api that provides these services? So we can dynamically add them instead of hardcoding?

**Comment by mrtnzlml** [comment]
Note: the services on the design are inaccurate - we do not provide "In-Flight meal" anymore for example.

**Comment by MRTNKCR** [comment]
The deeplinks are here https://paper.dropbox.com/doc/MMB-Deeplinks-NxiT0ZiaZP1sl7qibRcMg, I'm seeking for answers for the other questions.

**Comment by MRTNKCR** [comment]
Ok, here they are:

1. When should this modal open? -> There is no modal (flight selection) - this selection is only on the Trip services screen (the screen in Zeplin is a design fail)
2. How do we know if a service has been ordered? -> In the webview, the user sends a request to book the service. The bookers manually proceed the request in Podio and the user sees the pending payment in MMB. He has 24 hours to pay for the service.
3. Is there any api that provides these services? So we can dynamically add them instead of hardcoding? -> Nope :-( This list is hardcoded.
